### ISSUE TITLE
I would like to ask if you will publish training tutorials

### ISSUE THREAD

**Issue by liubaoning111** [mahmoudgamal0/Pulpy3D#2]

**Comment by mahmoudgamal0** [comment]
If you please could elaborate more on what do you mean exactly by training tutorials?

**Comment by liubaoning111** [comment]
I would like to know how you train it. Can configs.yml replace relevant files in cofigs folder?

**Comment by mahmoudgamal0** [comment]
You can follow the README for loading the dataset and for the required specifications of the hardware setup.
In the configs directory, there are important and required configurations such as `augmentation.yml` and `preprocessing.yml`.

The name of the configuration file is irrelevant as you provide it in the command line. You can customize your own config file but I suggest that you take a copy of what we provided and tune it as it suits you.

Of course you can also alter the preprocessing and augmentation techniques used by altering the values in the relevant configuration files
