### ISSUE TITLE
May I ask if there are any other ways to share the dataset

### ISSUE THREAD

**Issue by lgh010319** [mahmoudgamal0/Pulpy3D#3]
Hello author, I am currently unable to download the dataset using Google Cloud Drive. Could you please send me a copy of the dataset

**Comment by mahmoudgamal0** [comment]
You could try and download it using the Ditto website https://ditto.ing.unimore.it/pulpy3d/
I will add it to the Readme

**Comment by lgh010319** [comment]
Thank you, author
